### ISSUE TITLE
Like to run the app in a portrait orientation, vertically stacked.

### ISSUE THREAD

**Issue by blackbear** [raspicamplayer/camplayer#12]
How hard would it be to set up a configuration to run n 16x9 devices in a 1xn orientation. I have my monitor mounted in portrait on the wall, and if I use any of the stock layouts, it gets horribly stretched.

Glad to help if it's something I can.

**Comment by blackbear** [comment]
I have this working, if you give me access I'll submit a pull request.
![IMG_1290](https://user-images.githubusercontent.com/109585/111658274-92315f80-87e2-11eb-81a1-05190b87b442.JPEG)

**Comment by raspicamplayer** [comment]
@blackbear 
Glad to see you got it working.
To issue a pull request, you have to fork this repository, make your changes and then a "pull request" button should popup.

**Comment by blackbear** [comment]
Pull request is in.
On 3/18/2021 1:51:43 PM, raspicamplayer ***@***.***> wrote:
@blackbear [https://github.com/blackbear]
Glad to see you got it working.
To issue a pull request, you have to fork this repository, make your changes and then a "pull request" button should popup.

**Comment by raspicamplayer** [comment]
https://github.com/raspicamplayer/camplayer/pull/13
