### ISSUE TITLE
Cannot stop camplayer via VNC Viewer

### ISSUE THREAD

**Issue by jhamilt0n** [raspicamplayer/camplayer#15]
pressing "q" does not work via vnc viewer.  Cannot get back to terminal or desktop GUI

**Comment by fredjethehulk** [comment]
i have also this problem if i put sudo systemctl stop camplayer.service i does quit but not with the q button i get black screen

**Comment by raspicamplayer** [comment]
Does "sudo systemctl stop camplayer.service" do the job?
