### ISSUE TITLE
Key Mappings

### ISSUE THREAD

**Issue by enush33C** [raspicamplayer/camplayer#22]
Hello,

The key mappings don't seem to work with a USB Number Pad only. Is there a way to change the key mappings? I'd like to use a number pad only next to the display to control it a bit. Currently things like space and escape aren't on the number pad, so I'd like to change those mappings to something else. Thanks!

**Comment by raspicamplayer** [comment]
Not officially supported, but you can change key codes directly in the source code:
https://github.com/raspicamplayer/camplayer/blob/master/camplayer/utils/constants.py#L36
