### ISSUE TITLE
demo show nothing

### ISSUE THREAD

**Issue by Fuzzo** [raspicamplayer/camplayer#37]
I followed all the instruction in README.md file but when i execute `camplayer --demo`, even if the console has no errors, i do not see anything.
What i'm missing?

**Comment by raspicamplayer** [comment]
Wild guess, using the wrong HDMI output? Otherwise provide a logfile: https://github.com/raspicamplayer/camplayer#check-logging-output

**Comment by Fuzzo** [comment]
I'm using it in a headless system. 
I expected to see something in X session using xrdp but I'll try to connect a monitor.

**Comment by cybermaus** [comment]
It is using OMXplayer, which is layering directly into the GPU chip. X has no idea anything is happening.
